default['maven']['build'] = '3.0.3'
default['maven']['release'] = '2'
default['maven']['package'] = 'java-maven'
default['maven']['lifecycle'] = 'stable'
default['maven']['settings'] = 'settings.xml'
default['maven']['repository'] = '/home/dmps/.m2/'
