/*
-- Query: SELECT * FROM asms.providers
-- Date: 2012-08-16 13:39
*/
use asms;

INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (12,'accuen',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,6,'at_turn_accuen','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (9,'adobe',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,NULL,NULL,'2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (7,'adtech',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,NULL,NULL,'2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (6,'advertising_com',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,NULL,NULL,'2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (4,'behavior',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,0,2,'tc','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (5,'bluekai','at_bk_bestbuy and at_bluekai_travel are required to allow business to include specific BK travel audiences as ''Session'' Elements in ACE to support ''ANDing''',1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,1,'bk,at_bk_bestbuy,at_bluekai_travel','2012-08-07 15:05:27',NULL,'2012-08-07 15:05:27');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (19,'cars',NULL,0,1,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,12,'atp_cars','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (16,'chase',NULL,0,0,1,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor','#ftp_mi_chase','rq0Vig0~H~',1,5,'at_x1_chase','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (10,'cobalt',NULL,0,0,1,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor','#ftp_mi_cobalt','?uLxv43K!g',1,7,'at_cobalt','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (15,'gap',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,10,'at_gap','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (14,'nord',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,9,'at_brighttag_nord','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (1,'predictive_general',NULL,0,0,0,1,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,14,NULL,'2012-08-03 16:13:45',NULL,'2012-08-03 15:55:47');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (3,'predictive_net',NULL,0,0,0,1,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,NULL,NULL,'2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (2,'predictive_oo',NULL,0,0,0,1,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,3,NULL,'2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (8,'predictive_oo_net',NULL,0,0,0,1,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,NULL,NULL,'2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (18,'proctorgamble',NULL,0,1,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,4,'at_audsci_proctorgamble','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (11,'scigineer',NULL,0,0,1,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor','#ftp_mi_sci','=KjU1=6pzx',1,15,'at_scigineer','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (13,'sears',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,8,'at_brighttag_sears','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (17,'southwest',NULL,0,0,1,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor','#ftp_mi_sthwest','MV%t$5c5je',1,11,'at_demdex_southwest','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
INSERT INTO `providers` (`providerId`,`name`,`description`,`isStreamingRequired`,`isPixelBasedStreamingRequired`,`isFtpRequired`,`isPredictive`,`jsonStreamingClass`,`ftpUsername`,`ftpPassword`,`ignoreProviderInbDPR`,`priority`,`aceElementType`,`lastModified`,`retireDate`,`createDate`) VALUES (20,'tv',NULL,1,0,0,0,'com.aol.at.ingestor.data.processor.StreamingGenericDataProcessor',NULL,NULL,1,13,'atp_lotame_tv','2012-08-03 16:13:45',NULL,'2012-08-03 16:12:39');
