/*
-- Query: SELECT * FROM asms.partners
-- Date: 2012-08-16 13:39
*/
use asms;

INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (2,'adcom','adcom',NULL,'http://cmap.at.ace.advertising.com/cfcm.ashx?providerId=1&userId=UTID',NULL,1,0,0,NULL,'2012-07-31 16:35:39',NULL,'2012-07-31 16:26:52');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (1,'bk','bk',NULL,'http://tags.bluekai.com/site/4470?id=UTID','https://stags.bluekai.com/site/4470?id=UTID',1,1,0,1,'2012-08-07 14:36:31',NULL,'2012-08-07 14:36:31');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (6,'brighttag','btag',NULL,'http://s.thebrighttag.com/cs?tp=ao&aolid=UTID','https://s.thebrighttag.com/cs?tp=ao&aolid=UTID',1,1,0,3,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (9,'brilig','brlg',NULL,'http://p.brilig.com/contact/bct?pid=D2AA3815-E594-474E-A205-671347055D87&_ct=pixel&puid=UTID','https://p.brilig.com/contact/bct?pid=D2AA3815-E594-474E-A205-671347055D87&_ct=pixel&puid=UTID',1,0,0,NULL,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (3,'cobalt','cblt',NULL,'http://dt.admission.net/retargeting/um.gif?network=1&nuid=UTID',NULL,1,0,0,NULL,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (8,'demdex','dmx',NULL,'http://dpm.demdex.net/ibs:dpid=416&dpuuid=UTID','https://dpm.demdex.net/ibs:dpid=416&dpuuid=UTID',1,1,0,4,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (13,'hmpg','hp',NULL,'http://www.aol.com/ids.jsp?id=UTID','https://www.aol.com/ids.jsp?id=UTID',1,0,0,NULL,'2012-08-14 16:34:35',NULL,'2012-08-14 16:34:35');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (14,'hmpg_ca','hp_ca',NULL,'http://www.aol.ca/ids.jsp?id=UTID','https://www.aol.ca/ids.jsp?id=UTID',1,0,0,NULL,'2012-08-14 16:34:35',NULL,'2012-08-14 16:34:35');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (17,'hmpg_de','hp_de',NULL,'http://www.aol.de/ids.jsp?id=UTID','https://www.aol.de/ids.jsp?id=UTID',1,0,0,NULL,'2012-08-14 16:34:35',NULL,'2012-08-14 16:34:35');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (15,'hmpg_fr','hp_fr',NULL,'http://www.aol.fr/ids.jsp?id=UTID','https://www.aol.fr/ids.jsp?id=UTID',1,0,0,NULL,'2012-08-14 16:34:35',NULL,'2012-08-14 16:34:35');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (16,'hmpg_uk','hp_uk',NULL,'http://www.aol.co.uk/ids.jsp?id=UTID','https://www.aol.co.uk/ids.jsp?id=UTID',1,0,0,NULL,'2012-08-14 16:34:35',NULL,'2012-08-14 16:34:35');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (11,'lotame','ltme',NULL,'http://bcp.crwdcntrl.net/5/c=1777/tp=AOLS/tpid=UTID',NULL,1,0,0,NULL,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (10,'pictela','pic',NULL,'http://www.pictela.net/custom/esi/utid_setter.esi?utid=UTID','https://www.pictela.net/custom/esi/utid_setter.esi?utid=UTID',1,0,0,NULL,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (4,'scigineer','sci',NULL,'http://dex04.deqwas.net/sync/ai.aspx?sid=UTID',NULL,1,0,0,NULL,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (12,'tapad','tapad',NULL,'http://pixel.tapad.com/audience-x/pxl.png?did=UTID','https://pixel.tapad.com/audience-x/pxl.png?did=UTID',1,0,0,NULL,'2012-08-01 17:05:31',NULL,'2012-08-01 17:05:16');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (5,'turn','turn',NULL,'http://d.p-td.com/r/dt/id/L21rdC80L21waWQvMzMxNTMzNg/mpuid/UTID','https://d.p-td.com/r/dt/id/L21rdC80L21waWQvMzMxNTMzNg/mpuid/UTID',1,1,0,2,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
INSERT INTO `partners` (`partnerId`,`name`,`partnerShortCode`,`description`,`href`,`secureHref`,`isAtxIdsyncRequired`,`isRtxIdsyncRequired`,`isNetworkIdsyncRequired`,`priority`,`lastModified`,`retireDate`,`createDate`) VALUES (7,'xplusone','xp1',NULL,'https://d.xp1.ru4.com/um?_r=1&_o=62795&_i=42102464&_u=UTID','https://d.xp1.ru4.com/um?_r=1&_o=62795&_i=42102464&_u=UTID',1,0,0,NULL,'2012-07-31 16:35:39',NULL,'2012-07-31 16:34:58');
